spring.application.name=SP_7_REST_Security_Q_16

jwt.secret=K9e25z91O+RHZ1c+scd1rIbgq5iXZnTbOaHrjXyJ9Mw=


spring.datasource.url=jdbc:mysql://localhost:3306/Spring_16?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=3141@MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.cache.type.=simple
spring.api.docs=true
spring.swagger-ui.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=INFO

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
