server:
  port: 8088

spring:
  application:
    name: rabbitmq-simple-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    exchange: orders.exchange
    queue: orders.created.queue
    routing-key: orders.created

